### ISSUE TITLE
SerialPort.list() returns empty when script run without sudo (Raspberry Pi)

### ISSUE THREAD

**Issue by mikelyndersOKCC** [serialport/node-serialport#2142] opened 2020-09-18 16:13 UTC
# Summary of Problem
- What are you trying to do?

I have developed an Electron Application that displays/graphs/analyzes data from several lab instruments with serial outputs. I have an "autoconnect" feature that use SerialPort.list() to get a list of the ports which I then try to query for serial numbers. This works fine on Windows (which I was using to develop) but now I am trying to deploy my application on several Raspberry Pi's.

- What happens?

SerialPort.list() returns an empty list `[]` when run in both Electron and in a minimal test script (see below) on the Raspberry Pi. However, I noticed that running the same script with `sudo` works as expected. Interestingly, I can connect to the port directly without `sudo` if I know the port name ahead of time ex: */dev/ttyUSB0*  

Also, `$ udevadm info -q path -n /dev/ttyUSB0` returns nothing but returns as expected with sudo : `$ sudo udevadm info -q path -n /dev/ttyUSB0`

Any ideas what's going on here? I imagine I shouldn't need `sudo` to get a list of ports, especially if I can connect to them without it. Also, as a sanity check, I ran a python script with pyserial which lists the ports without `sudo` on the same Raspberry Pi, so I don't think I have a weird udev/permissions setup.

- What should have happened?

SerialPort.list() should return a list of ports even when the script is run without `sudo`

### Code to Reproduce the Issue

```js
const SerialPort = require('serialport')

SerialPort.list().then(ports=>console.log(ports), err=>console.log(err))

```

### Versions, Operating System and Hardware

- SerialPort@9.0.1
- Node.js v14.11.0
- Linux (Raspberry Pi 4) Raspberry Pi OS August 2020
- Hardware and chipset? RPi -> USB/RS-232 Adapters -> Generic Serial Device (Laboratory Instrument)

**Comment by fivdi** [comment] 2020-09-19 03:55
Duplicate of #2141

**Closed by fivdi** 2020-09-19 03:55 UTC
